language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - rbx-2
  - jruby
script: rspec
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
cache: bundler
